### ISSUE TITLE
vpn configuration should be always the last option

### ISSUE THREAD

**Issue by muescha** [deanishe/alfred-vpn-manager#10]
the option `vpn configuration` should be always the last option

i have `connection1` and `connection2`

if i type `vpn` then when disconneted the order is:

1. `connection1` 
2. `vpn configuration`
3. `connection2`

if i type `vpn` then when conneted the order is:

1. `vpn configuration`
2. `connection1` 
3. `connection2`

i expect always:

1. `connection1` 
2. `connection2`
3. `vpn configuration`

**Comment by deanishe** [comment]
There's nothing the workflow can do about that.

The configuration is under a separate keyword (`vpnconf`). They're getting mixed up because you're looking at Alfred's full results, not just the workflow's. That is to say, you haven't "entered" the workflow where you're only seeing its results (which don't include the configuration): any apps or other keywords matching "vpn" will also appear.

Your best bet is to either get into the habit of typing `vpn ` (with a trailing space) or to change the keyword to something like `.vpn` that won't match anything else.

**Comment by muescha** [comment]
`vpn ` (woth space works)

Maybe put thr configuration into `vpn conf` so you can change the order

One point: take the conf icon different than the connected icon. It is confusiung for me and i habe alway to think about which is which when they have the same green icon.

**Comment by deanishe** [comment]
> Maybe put thr configuration into vpn conf so you can change the order

It doesn't work that way. Like I said, Alfred is doing the ordering at that point, based on *your* usage.

Changing the keyword to `vpn conf` will just make it also appear when you enter `vpn ` (with space). Essentially, you're seeing it near the top of the results because that's where you've trained Alfred to show it.

On top of that, the only way I, as the workflow author, can determine the order of results is if I deliberately prevent Alfred learning from your usage. The workflow does this *only* when a VPN is connected and you haven't entered a search query, in order to be able to force those connections to the top.

I'm not going to turn it off under other circumstances because then it will never learn to associate connections with the queries you enter. Which would suck.

> It is confusiung for me and i habe alway to think about which is which when they have the same green icon

If you get into the habit of entering `vpn ` instead of just `vpn`, you won't ever see it again.

I will look into making the configuration item look different to the main workflow item, however. It's not just the icon: the text also looks very similar at a glance.
